### ISSUE TITLE
Kesalahan pada cek ongkir (getCost)

### ISSUE THREAD

**Issue by komputronika** [satriaajiputra/raja-ongkir-api#1]
**Pada baris 167:**
CURLOPT_POSTFIELDS => "origin=501&destination=114&weight=1700&courier=jne",

**Seharusnya:**			
CURLOPT_POSTFIELDS => "origin=$from&destination=$to&weight=$weight&courier=$courier",

**Comment by satriaajiputra** [comment]
Terimakasih koreksinya.
### Fixed script
[Change static post fields](https://github.com/satriaajiputra/raja-ongkir-api/commit/aa1ac6a6078bb58aee5be92b5358caaede7cd1ef)
